/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ContractController;
import controllers.EmployeeController;
import helpers.Formatacao;
import helpers.Validacao;
import java.util.Date;
import javax.swing.JOptionPane;
import models.Contract;
import models.Employee;

/**
 *
 * @author lucas
 */
public class ContractCRUDView extends javax.swing.JFrame {

    /**
     * Creates new form ContractCRUDView
     */
    
    int contractID;
    public ContractCRUDView() {
        initComponents();
        ContractController cc = new ContractController();
        cc.populateTable(jTable1, null);
        Formatacao.formatarData(this.jTXTDataFinal);
        Formatacao.formatarData(this.jTXTDataFinalEditar);
        Formatacao.formatarData(this.jTXTDataInicial);
        Formatacao.formatarData(this.jTXTDataInicialEditar);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTXTDataInicial = new javax.swing.JFormattedTextField();
        jTXTDataFinal = new javax.swing.JFormattedTextField();
        jTXTMulta = new javax.swing.JFormattedTextField();
        jTXTValor = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTXTDataInicialEditar = new javax.swing.JFormattedTextField();
        jTXTDataFinalEditar = new javax.swing.JFormattedTextField();
        jTXTMultaEditar = new javax.swing.JFormattedTextField();
        jTXTValorEditar = new javax.swing.JFormattedTextField();
        jButton5 = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jCheckBoxCartaoEditar = new javax.swing.JCheckBox();
        jCheckBoxBoletoEditar = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contratos");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Data Inicial:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 63, 94, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Data Final:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 124, 84, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Multa:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 186, 49, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Valor total:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 298, 87, 22);
        jPanel2.add(jTXTDataInicial);
        jTXTDataInicial.setBounds(152, 63, 150, 28);
        jPanel2.add(jTXTDataFinal);
        jTXTDataFinal.setBounds(152, 124, 150, 28);
        jPanel2.add(jTXTMulta);
        jTXTMulta.setBounds(152, 186, 150, 28);
        jPanel2.add(jTXTValor);
        jTXTValor.setBounds(145, 298, 150, 28);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(433, 332, 100, 23);

        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(592, 332, 92, 23);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox1.setText("Cartão");
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(40, 250, 81, 23);

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox2.setText("Boleto");
        jPanel2.add(jCheckBox2);
        jCheckBox2.setBounds(210, 240, 75, 31);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Registrar", jPanel1);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Consultar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Editar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Remover");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Cancelar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton7)
                .addGap(34, 34, 34)
                .addComponent(jButton6)
                .addGap(64, 64, 64)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Consultar/Remover", jPanel3);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Data Inicial:");
        jPanel7.add(jLabel7);
        jLabel7.setBounds(40, 63, 94, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Data Final:");
        jPanel7.add(jLabel8);
        jLabel8.setBounds(40, 124, 84, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Multa:");
        jPanel7.add(jLabel9);
        jLabel9.setBounds(40, 186, 49, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Valor total:");
        jPanel7.add(jLabel11);
        jLabel11.setBounds(40, 298, 87, 22);
        jPanel7.add(jTXTDataInicialEditar);
        jTXTDataInicialEditar.setBounds(152, 63, 150, 28);
        jPanel7.add(jTXTDataFinalEditar);
        jTXTDataFinalEditar.setBounds(152, 124, 150, 28);
        jPanel7.add(jTXTMultaEditar);
        jTXTMultaEditar.setBounds(152, 186, 150, 28);
        jPanel7.add(jTXTValorEditar);
        jTXTValorEditar.setBounds(145, 298, 150, 28);

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5);
        jButton5.setBounds(433, 332, 75, 23);

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        jPanel7.add(Editar);
        Editar.setBounds(592, 332, 92, 23);
        jPanel7.add(jLabel12);
        jLabel12.setBounds(400, 10, 280, 380);

        jCheckBoxCartaoEditar.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxCartaoEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBoxCartaoEditar.setText("Cartão");
        jPanel7.add(jCheckBoxCartaoEditar);
        jCheckBoxCartaoEditar.setBounds(40, 240, 77, 31);

        jCheckBoxBoletoEditar.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxBoletoEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBoxBoletoEditar.setText("Boleto");
        jPanel7.add(jCheckBoxBoletoEditar);
        jCheckBoxBoletoEditar.setBounds(170, 240, 75, 31);

        jTabbedPane1.addTab("Editar", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ContractController cc = new ContractController();
        cc.populateTable(jTable1, null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        boolean ok = true;
        Contract ct = new Contract();
        
        if(Validacao.notNull(this.jTXTDataInicial.getText())){
            String[] split = this.jTXTDataFinal.getText().split("/");
            int dia = Integer.parseInt(split[0]);
            int mes = Integer.parseInt(split[1]);
            int ano = Integer.parseInt(split[2]);
            Date data = new Date(ano, mes, dia);
            
            ct.setContract_date(data);
        }
        else{
            JOptionPane.showMessageDialog(null, "Entre com a data inicial do contrato!");
            this.jTXTDataInicial.requestFocus();
            ok = false;
        }
        if(Validacao.notNull(this.jTXTDataFinal.getText())){
            String[] split = this.jTXTDataFinal.getText().split("/");
            int dia = Integer.parseInt(split[0]);
            int mes = Integer.parseInt(split[1]);
            int ano = Integer.parseInt(split[2]);
            Date data = new Date(ano, mes, dia);
            
            ct.setContract_cancel_date(data);
        }
        else{
            JOptionPane.showMessageDialog(null, "Entre com a data final do contrato!");
           this.jTXTDataFinal.requestFocus();
            ok = false;
        }
        if(Validacao.notNull(this.jTXTValor.getText())){
            ct.setContract_value(Double.parseDouble(this.jTXTValor.getText()));
        }
        else{
            JOptionPane.showMessageDialog(null, "Entre com o valor do contrato");
            this.jTXTValor.requestFocus();
            ok = false;
        }
        if (Validacao.notNull(this.jTXTMulta.getText())){
            ct.setPenalty(Integer.parseInt(this.jTXTMulta.getText()));
        }
        else{
            JOptionPane.showMessageDialog(null, "Entre com o valor da multa");
            ok = false;
        }
        if(jCheckBox1.isSelected()){
            ct.setPayment_type("Cartão");
        }
        else if (jCheckBox2.isSelected()){
            ct.setPayment_type("Boleto");
        }
        
        ContractController cc = new ContractController();
        
        if(ok){
            cc.create(ct);
            cc.populateTable(jTable1,"");
        }
        else {
            JOptionPane.showMessageDialog(null, "Verificar entradas de dados!");
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.jTXTValorEditar.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 5)));
        this.jTXTDataInicialEditar.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 1)));
        this.jTXTDataFinalEditar.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 2)));
        this.jTXTMultaEditar.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 3)));
        this.contractID = Integer.parseInt(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0)));

        
        jTabbedPane1.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
        boolean ok = true;
        Contract ct = new Contract();
        
        if(Validacao.notNull(this.jTXTDataInicialEditar.getText())){
            String[] split = this.jTXTDataFinalEditar.getText().split("/");
            int dia = Integer.parseInt(split[0]);
            int mes = Integer.parseInt(split[1]);
            int ano = Integer.parseInt(split[2]);
            Date data = new Date(ano, mes, dia);
            
            ct.setContract_date(data);
        }
        else{
            JOptionPane.showMessageDialog(null, "Entre com a data inicial do contrato!");
            this.jTXTDataInicialEditar.requestFocus();
            ok = false;
        }
        if(Validacao.notNull(this.jTXTDataFinalEditar.getText())){
            String[] split = this.jTXTDataFinalEditar.getText().split("/");
            int dia = Integer.parseInt(split[0]);
            int mes = Integer.parseInt(split[1]);
            int ano = Integer.parseInt(split[2]);
            Date data = new Date(ano, mes, dia);
            
            ct.setContract_cancel_date(data);
        }
        else{
            JOptionPane.showMessageDialog(null, "Entre com a data final do contrato!");
           this.jTXTDataFinalEditar.requestFocus();
            ok = false;
        }
        if(Validacao.notNull(this.jTXTValorEditar.getText())){
            ct.setContract_value(Double.parseDouble(this.jTXTValorEditar.getText()));
        }
        else{
            JOptionPane.showMessageDialog(null, "Entre com o valor do contrato");
            this.jTXTValorEditar.requestFocus();
            ok = false;
        }
        if (Validacao.notNull(this.jTXTMultaEditar.getText())){
            ct.setPenalty(Integer.parseInt(this.jTXTMultaEditar.getText()));
        }
        else{
            JOptionPane.showMessageDialog(null, "Entre com o valor da multa");
            ok = false;
        }
        if(jCheckBoxCartaoEditar.isSelected()){
            ct.setPayment_type("Cartão");
        }
        else if (jCheckBoxBoletoEditar.isSelected()){
            ct.setPayment_type("Boleto");
        }
        
        ContractController cc = new ContractController();
        
        if(ok){
            cc.update(ct, contractID);
        }
        else {
            JOptionPane.showMessageDialog(null, "Verificar entradas de dados!");
        }
        
        
        
    }//GEN-LAST:event_EditarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.contractID = Integer.parseInt(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0)));
        ContractController controller = new ContractController();
        controller.delete(this.contractID);
        controller.populateTable(jTable1, "");
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContractCRUDView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContractCRUDView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContractCRUDView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContractCRUDView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContractCRUDView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBoxBoletoEditar;
    private javax.swing.JCheckBox jCheckBoxCartaoEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jTXTDataFinal;
    private javax.swing.JFormattedTextField jTXTDataFinalEditar;
    private javax.swing.JFormattedTextField jTXTDataInicial;
    private javax.swing.JFormattedTextField jTXTDataInicialEditar;
    private javax.swing.JFormattedTextField jTXTMulta;
    private javax.swing.JFormattedTextField jTXTMultaEditar;
    private javax.swing.JFormattedTextField jTXTValor;
    private javax.swing.JFormattedTextField jTXTValorEditar;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
